# Generated by Django 4.0.3 on 2022-05-04 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='telephoneNB',
        ),
    ]
