# Generated by Django 4.0.3 on 2022-05-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_state_shippingaddress_telephonenb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='telephoneNB',
            field=models.CharField(max_length=10),
        ),
    ]
