# Generated by Django 4.0.3 on 2022-05-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_buy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
