# Generated by Django 4.0.3 on 2022-05-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderitem_price_buy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_bestseller',
            new_name='is_special',
        ),
    ]
